---
title: "BN"
author: "Yirao Zhang"
date: "13/05/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data<-read.csv("/Users/yiraozhang/Desktop/cyanobacteria_pgm/cyanobacterial-bloom-prediction/cyano_train.csv")
colnames(data)<-c("index","Precipitation","Solar radiation","date","pH","DP","TKN","DO","Turb","Temp","Cyanobacteria")
drop <- c("index","date")
data<-data[,!(names(data) %in% drop)]
data$Cyanobacteria<-as.double(data$Cyanobacteria)
data
```
```{r}
library(bnlearn)
library(Rgraphviz)
net1<-tabu(data)
graphviz.plot(net1)
```
```{r}
bl = matrix(c("Precipitation","Solar radiation","Temp","Solar radiation","TKN","Solar radiation","DO","Solar radiation","pH","Solar radiation","DO","Temp","pH","Temp","Precipitation","Temp","Solar radiation","Temp"), ncol = 2, byrow = TRUE)
wl = matrix(c("DP","Cyanobacteria","Temp","Cyanobacteria","TKN","Cyanobacteria","Solar radiation","Cyanobacteria","pH","Cyanobacteria"), ncol = 2, byrow = TRUE)
net<-tabu(data, blacklist=bl, whitelist = wl)
graphviz.plot(net)
```
```{r}

```

```{r}
fitted<-bn.fit(net1, data)
fitted
```
```{r}
bn.fit.qqplot(fitted)
```
```{r}
#testing set
test<-read.csv("/Users/yiraozhang/Desktop/cyanobacteria_pgm/cyanobacterial-bloom-prediction/cyano_test.csv")
colnames(test)<-c("index","Precipitation","Solar radiation","date","pH","DP","TKN","DO","Turb","Temp","Cyanobacteria")
drop <- c("index","date")
test<-test[,!(names(test) %in% drop)]
test$Cyanobacteria<-as.double(test$Cyanobacteria)
test
```
```{r}
pred = predict(fitted, "Cyanobacteria", test)
cbind(pred, test[, "Cyanobacteria"]) 
```
```{r}
library(forecast)
accuracy(f = pred, x = test[, "Cyanobacteria"])
```